# Generated by Django 4.1.7 on 2023-04-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_img', models.ImageField(upload_to='sliderimg/')),
                ('sl_title', models.CharField(max_length=100, verbose_name='Заголовок слайдера')),
                ('sl_text', models.CharField(max_length=250, verbose_name='Текст слайдера')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
