# Generated by Django 4.1.7 on 2023-04-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='sl_css',
            field=models.CharField(default='-', max_length=50, null=True, verbose_name='CSS класс'),
        ),
        migrations.AlterField(
            model_name='cmsslider',
            name='sl_img',
            field=models.ImageField(upload_to='sliderimg/', verbose_name='Картинка слайдера'),
        ),
    ]
